# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: ml-artreg-digital-pathology-p

trigger: 
- main

stages:
 - stage: GitHub
   pool:
    name: Azure Pipelines
   jobs:
    - job: FetchGitHub
      steps:
        - task: Docker@2
          name: Debian
          displayName: 'Build debian base image'
          inputs:
            repository: '$(GCR.Name)/base_image_debian'
            command: build
            Dockerfile: pathology/base_docker_images/base_py_debian_docker/Dockerfile
            tags: 'latest'
        - task: Bash@3
          displayName: Save Docker Image
          inputs:
            targetType: 'inline'
            script: |
             docker save $(GCR.Name)/base_image_debian:latest -o $(System.DefaultWorkingDirectory)/image_file.tar
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/image_file.tar'
            artifact: 'IMAGE_ARTIFACT'
            #publishLocation: 'pipeline'             
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact'
          enabled: false
          name: Publish
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)
            artifact: 'github_oss'        
        - task: Docker@2
          displayName: 'Build open cv base image'
          enabled: false
          inputs:
            repository: '$(GCR.Name)/base_image_open_cv'
            command: build
            Dockerfile: pathology/base_docker_images/base_py_opencv_docker/Dockerfile
            tags: 'latest'
            arguments: '--build-arg BASE_CONTAINER=$(GCR.Name)/base_image_debian:latest'
        - task: Docker@2
          displayName: 'Build transformation base image'
          enabled: false
          inputs:
            repository: '$(GCR.Name)/base_image_transformation'
            command: build
            Dockerfile: pathology/base_docker_images/base_transformation_docker/Dockerfile
            tags: 'latest'
            arguments: '--build-arg BASE_CONTAINER=$(GCR.Name)/base_image_open_cv:latest'

        - task: Docker@2
          displayName: 'Build transformation image'
          enabled: false
          inputs:
            repository: '$(GCR.Name)/test_transformation'
            command: build
            Dockerfile: pathology/transformation_pipeline/Dockerfile
            tags: 'latest'
            arguments: '--build-arg BASE_CONTAINER=$(GCR.Name)/base_image_transformation:latest'

        - script: 'docker image ls'
          displayName: 'List Docker images'

 - stage: ADO
   pool:
    name: MCC Applications
   jobs:
    - job: BuildInADO
      steps:
        - checkout: none

        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'MY_ARTIFACT'
            targetPath: '$(System.DefaultWorkingDirectory)'
        - task: Bash@3
          displayName: Load Docker Image
          inputs:
            targetType: 'inline'
            script: |      
              docker load --input $(System.DefaultWorkingDirectory)/image_file.tar
              docker tag $(GCR.Name)/base_image_debian:latest $(GCR.Name)/base_image_debian:latest      
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Pipeline Artifact'
          enabled: false
          inputs:
            artifactName: 'github_oss'
            targetPath: '$(System.DefaultWorkingDirectory)'
        - task: mclm.MCCVaultIntegration.MCCVaultIntegration.MCCVaultIntegration@1
          name: VaultOutput
          displayName: 'MCC Vault Integration'
          inputs:
            vaultActionType: 'gcpCreds'
            gcpSecretType: 'token'
            GcpCredRoleset: $(Vault.Roleset)
            Namespace: $(Vault.Namespace)
            RoleId: $(Vault.RoleId)
            SecretId: $(Vault.SecretId)
            HostUri: $(Vault.Address)

        - bash: echo $(VaultOutput.VaultResult)

        - script: 'docker login -u oauth2accesstoken -p $SA_TOKEN https://$(GCR.Name)'
          displayName: 'Authenticate to Container Registry'
          env:
            SA_TOKEN: $(VaultOutput.VaultResult)

        - task: PrismaCloud.build-release-task.custom-build-release-task.prisma-cloud-compute-scan@3
          displayName: 'Prisma Cloud Compute Scan'
          inputs:
            twistlockService: 'Prisma Compute'
            artifact: '$(GCR.Name)/base_image_debian:latest'
          continueOnError: false
        - task: Docker@2
          displayName: 'Publish Container Image'
          inputs:
            repository: '$(GCR.Name)/base_image_debian:latest'
            command: push       
